name: deploy
on:
  push:
    branches:
      - master
env:
 LOGIN: ${{ secrets.DOCKER_LOGIN }}
 NAME: ${{ secrets.DOCKER_NAME }}
 TOKEN: ${{ secrets.BOT_TOKEN }}
jobs:
  docker_push:
    runs-on: [ubuntu-latest]
    steps:
    - name: Login to docker.io
      run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - uses: actions/checkout@master
    - name: create configure
      run: echo ${{ secrets.BOT_TOKEN }} >> configure.py 
    - name: Build image
      run: docker compose build
      #run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f dockerfile .
    - name: Push image to docker.io
      run: docker push $LOGIN/$NAME:${GITHUB_REF:11}